{% set name = "gmatelastoplasticqpot3d" %}
{% set version = "0.5.0" %}
{% set sha256 = "779d8ca95053f7cc83a4b360a2b58724e12f871dff58092bbb4109a086e38fad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlasticQPot3d/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
  run:
    - xtensor

test:
  commands:
    - test -d ${PREFIX}/include/GMatElastoPlasticQPot3d  # [unix]
    - test -f ${PREFIX}/include/GMatElastoPlasticQPot3d/Cartesian3d.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GMatElastoPlasticQPot3d/GMatElastoPlasticQPot3dConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GMatElastoPlasticQPot3d\Cartesian3d.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GMatElastoPlasticQPot3dConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GMatElastoPlasticQPot3d
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Elasto-plastic model based on a manifold of quadratic potentials (C++ header-only library).
  description: Elasto-plastic model based on a manifold of quadratic potentials (C++ header-only library).
  doc_url: https://github.com/tdegeus/GMatElastoPlasticQPot3d
  dev_url: https://github.com/tdegeus/GMatElastoPlasticQPot3d

extra:
  recipe-maintainers:
    - tdegeus
